/* Generated by Together */

//@CheckItem@ Refactor-yangfeng-20040409 注释掉不可用代码
package com.aspire.common.config;

public class ConfigFactory
{
    private static SystemConfig systemConfig = null;
    //private static ConfigFactory instance = null;

    private ConfigFactory()
    {
    }

    public static SystemConfig getSystemConfig()
    {
        //initialize the ConfigFactory class
        /*
        synchronized (ConfigFactory.class){
            if (instance == null){
                instance = new ConfigFactory();
            }
        }
        */
        //get the SystemConfig instance
        synchronized (SystemConfig.class){
            if (systemConfig == null){
                systemConfig = new SystemConfig();
                //systemConfig.init();
            }
        }
        return systemConfig;

    }

}
