


update T_R_EXPORTSQL t set t.exportbyauto = '1' where t.id >=15;


---------------------------------
---回滚分省权限数据-------------
---------------------------------
delete from  t_category_usergroup   t where t.code in ('ssms_category_content_SH','ssms_category_class_SH','ssms_category_content_FJ','ssms_category_class_FJ','ssms_category_content_AH','ssms_category_class_AH','ssms_category_content_JX','ssms_category_class_JX','ssms_category_content_GD','ssms_category_class_GD','ssms_category_content_GX','ssms_category_class_GX','ssms_category_content_HI','ssms_category_class_HI','ssms_category_content_HN','ssms_category_class_HN','ssms_category_content_HB','ssms_category_class_HB','ssms_category_content_SC','ssms_category_class_SC','ssms_category_content_YN','ssms_category_class_YN','ssms_category_content_GZ','ssms_category_class_GZ','ssms_category_content_CQ','ssms_category_class_CQ','ssms_category_content_SN','ssms_category_class_SN','ssms_category_content_XZ','ssms_category_class_XZ','ssms_category_content_BJ','ssms_category_class_BJ','ssms_category_content_TJ','ssms_category_class_TJ','ssms_category_content_NMG','ssms_category_class_NMG','ssms_category_content_SD','ssms_category_class_SD','ssms_category_content_LN','ssms_category_class_LN','ssms_category_content_JN','ssms_category_class_JN','ssms_category_content_HLJ','ssms_category_class_HLJ','ssms_category_content_HA','ssms_category_class_HA','ssms_category_content_HE','ssms_category_class_HE','ssms_category_content_SX','ssms_category_class_SX','ssms_category_content_NX','ssms_category_class_NX','ssms_category_content_GS','ssms_category_class_GS','ssms_category_content_QH','ssms_category_class_QH','ssms_category_content_XJ','ssms_category_class_XJ');
delete from  t_category_single   t where t.USERID in ('ssms_category_content_SH','ssms_category_class_SH','ssms_category_content_FJ','ssms_category_class_FJ','ssms_category_content_AH','ssms_category_class_AH','ssms_category_content_JX','ssms_category_class_JX','ssms_category_content_GD','ssms_category_class_GD','ssms_category_content_GX','ssms_category_class_GX','ssms_category_content_HI','ssms_category_class_HI','ssms_category_content_HN','ssms_category_class_HN','ssms_category_content_HB','ssms_category_class_HB','ssms_category_content_SC','ssms_category_class_SC','ssms_category_content_YN','ssms_category_class_YN','ssms_category_content_GZ','ssms_category_class_GZ','ssms_category_content_CQ','ssms_category_class_CQ','ssms_category_content_SN','ssms_category_class_SN','ssms_category_content_XZ','ssms_category_class_XZ','ssms_category_content_BJ','ssms_category_class_BJ','ssms_category_content_TJ','ssms_category_class_TJ','ssms_category_content_NMG','ssms_category_class_NMG','ssms_category_content_SD','ssms_category_class_SD','ssms_category_content_LN','ssms_category_class_LN','ssms_category_content_JN','ssms_category_class_JN','ssms_category_content_HLJ','ssms_category_class_HLJ','ssms_category_content_HA','ssms_category_class_HA','ssms_category_content_HE','ssms_category_class_HE','ssms_category_content_SX','ssms_category_class_SX','ssms_category_content_NX','ssms_category_class_NX','ssms_category_content_GS','ssms_category_class_GS','ssms_category_content_QH','ssms_category_class_QH','ssms_category_content_XJ','ssms_category_class_XJ');



-----------------------------------------------
---下述脚本要在portalwww@MMportal 下执行------
-----------------------------------------------

delete from  MP_T_ROLE   where t.role_key in ('ah_manager','bj_manager','cq_manager','fj_manager','gd_manager','gs_manager','gx_manager','gz_manager','ha_manager','hb_manager','he_manager','hi_manager','hlj_manager','hn_manager','jn_manager','js_manager','jx_manager','ln_manager','nmg_manager','nx_manager','qh_manager','sc_manager','sd_manager','sh_manager','sn_manager','sx_manager','tj_manager','xj_manager','xz_manager','yn_manager');
delete from  mp_t_role_operation   t where t.OPERATION_KEY in ('ssms_category_content_SH','ssms_category_class_SH','ssms_category_content_FJ','ssms_category_class_FJ','ssms_category_content_AH','ssms_category_class_AH','ssms_category_content_JX','ssms_category_class_JX','ssms_category_content_GD','ssms_category_class_GD','ssms_category_content_GX','ssms_category_class_GX','ssms_category_content_HI','ssms_category_class_HI','ssms_category_content_HN','ssms_category_class_HN','ssms_category_content_HB','ssms_category_class_HB','ssms_category_content_SC','ssms_category_class_SC','ssms_category_content_YN','ssms_category_class_YN','ssms_category_content_GZ','ssms_category_class_GZ','ssms_category_content_CQ','ssms_category_class_CQ','ssms_category_content_SN','ssms_category_class_SN','ssms_category_content_XZ','ssms_category_class_XZ','ssms_category_content_BJ','ssms_category_class_BJ','ssms_category_content_TJ','ssms_category_class_TJ','ssms_category_content_NMG','ssms_category_class_NMG','ssms_category_content_SD','ssms_category_class_SD','ssms_category_content_LN','ssms_category_class_LN','ssms_category_content_JN','ssms_category_class_JN','ssms_category_content_HLJ','ssms_category_class_HLJ','ssms_category_content_HA','ssms_category_class_HA','ssms_category_content_HE','ssms_category_class_HE','ssms_category_content_SX','ssms_category_class_SX','ssms_category_content_NX','ssms_category_class_NX','ssms_category_content_GS','ssms_category_class_GS','ssms_category_content_QH','ssms_category_class_QH','ssms_category_content_XJ','ssms_category_class_XJ');




delete DBVERSION where PATCHVERSION = 'MM2.0.0.0.059_SSMS' and LASTDBVERSION = 'MM2.0.0.0.047_SSMS';
commit;