DROP TABLE T_A_PUSH;
DROP TABLE T_A_CONTENT_DOWNCOUNT;
DROP TABLE t_a_gamecontent_seriesid


delete DBVERSION where PATCHVERSION = 'MM2.0.0.0.047_SSMS' and LASTDBVERSION = 'MM2.0.0.0.045_SSMS';
commit;