
alter table t_r_gcontent drop column isCmpassApp;

alter table t_r_gcontent drop column logo7;















create or replace view v_d_gcontent as
select
  t1."ID",t1."NAME",t1."CATENAME",t1."APPCATENAME",t1."APPCATEID",t1."SPNAME",t1."ICPCODE",t1."ICPSERVID",t1."CONTENTTAG",t1."SINGER",t1."PRICE",t1."EXPIRE",t1."AUDITIONURL",t1."INTRODUCTION",t1."NAMELETTER",t1."SINGERLETTER",t1."DOWNLOADTIMES",t1."SETTIMES",t1."BIGCATENAME",t1."CONTENTID",t1."COMPANYID",t1."PRODUCTID",t1."KEYWORDS",t1."CREATEDATE",t1."MARKETDATE",t1."LUPDDATE",t1."LANGUAGE",t1."WWWPROPAPICTURE1",t1."WWWPROPAPICTURE2",t1."WWWPROPAPICTURE3",t1."CLIENTPREVIEWPICTURE1",t1."CLIENTPREVIEWPICTURE2",t1."CLIENTPREVIEWPICTURE3",t1."CLIENTPREVIEWPICTURE4",t1."PROVIDER",t1."HANDBOOK",t1."MANUAL",t1."HANDBOOKPICTURE",t1."USERGUIDE",t1."USERGUIDEPICTURE",t1."GAMEVIDEO",t1."LOGO1",t1."LOGO2",t1."LOGO3",t1."LOGO4",t1."CARTOONPICTURE",t1."DEVICENAME",t1."DEVICENAME02",t1."DEVICENAME03",t1."DEVICENAME04",t1."DEVICENAME05",t1."DEVICENAME06",t1."DEVICENAME07",t1."DEVICENAME08",t1."DEVICENAME09",t1."DEVICENAME10",t1."DEVICENAME11",t1."DEVICENAME12",t1."DEVICENAME13",t1."DEVICENAME14",t1."DEVICENAME15",t1."DEVICENAME16",t1."DEVICENAME17",t1."DEVICENAME18",t1."DEVICENAME19",t1."DEVICENAME20",t1."DAYSEARCHTIMES",t1."WEEKSEARCHTIMES",t1."MONTHSEARCHTIMES",t1."SEARCHTIMES",t1."DAYSCANTIMES",t1."WEEKSCANTIMES",t1."MONTHSCANTIMES",t1."SCANTIMES",t1."DAYORDERTIMES",t1."WEEKORDERTIMES",t1."MONTHORDERTIMES",t1."ORDERTIMES",t1."DAYCOMMENTTIMES",t1."WEEKCOMMENTTIMES",t1."MONTHCOMMENTTIMES",t1."COMMENTTIMES",t1."DAYMARKTIMES",t1."WEEKMARKTIMES",t1."MONTHMARKTIMES",t1."MARKTIMES",t1."DAYCOMMENDTIMES",t1."WEEKCOMMENDTIMES",t1."MONTHCOMMENDTIMES",t1."COMMENDTIMES",t1."DAYCOLLECTTIMES",t1."WEEKCOLLECTTIMES",t1."MONTHCOLLECTTIMES",t1."COLLECTTIMES",t1."AVERAGEMARK",t1."ISSUPPORTDOTCARD",t1."PROGRAMSIZE",t1."PROGRAMID",t1."ONLINETYPE",t1."VERSION",t1."PICTURE1",t1."PICTURE2",t1."PICTURE3",t1."PICTURE4",t1."PICTURE5",t1."PICTURE6",t1."PICTURE7",t1."PICTURE8",t1."PLATFORM",t1."CHARGETIME",t1."BRAND",t1."SERVATTR",t1."SUBTYPE",t1."PVCID",t1."CITYID",t1."FULLDEVICENAME",t1."MATCH_DEVICEID",t1."EXPPRICE",t1."FULLDEVICEID",t1."MODAYORDERTIMES",t1."PLUPDDATE",t1."OTHERNET",t1."RICHAPPDESC",t1."ADVERTPIC",t1."PRICETYPE",t1."COMPAREDNUMBER",t1."FUNCDESC",t1."MSTATUS",t1."LOGO5",
  t2.mobileprice,
  t2.servType,
  t2.chargeType,
  t2.chargeDesc,
  t3.type as xtype,
  t1.logo6,
  t1.ismmtoevent,
  t1.copyrightFlag,t1.mapname
from t_r_gcontent t1,
   v_a_service t2,
   t_r_base t3
   --t_a_android_list t4
where
   t1.contentid=t2.contentid
   and
  t1.id=t3.id;




















commit;




















